export const appActionType = {
  FETCH_LOGS: 'FETCH_LOGS',
  RESET_LOGS: 'RESET_LOGS'
};

export const authUserActionType = {
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  SET_AUTHENTICATED: 'SET_AUTHENTICATED',
  UNSET_AUTHENTICATED: 'UNSET_AUTHENTICATED',
  MERGE_EMPLOYEE_LIST: 'MERGE_EMPLOYEE_LIST',
  RESET_EMPLOYEE_LIST: 'RESET_EMPLOYEE_LIST',
  MERGE_USER_LIST: 'MERGE_USER_LIST',
  RESET_USER_LIST: 'RESET_USER_LIST',
  MERGE_USER_DATA: 'MERGE_USER_DATA',
  RESET_USER_DATA: 'RESET_USER_DATA'
};

export const servicesActionType = {
  MERGE_SERVICES: 'MERGE_SERVICES',
  RESET_SERVICES: 'RESET_SERVICES'
};

export const projectActionType = {
  MERGE_PROJECT: 'MERGE_PROJECT',
  RESET_PROJECT: 'RESET_PROJECT',
  MERGE_PROJECT_COMMENT: 'MERGE_PROJECT_COMMENT',
  RESET_PROJECT_COMMENT: 'RESET_PROJECT_COMMENT',
  MERGE_PROJECT_DETAILS: 'MERGE_PROJECT_DETAILS',
  RESET_PROJECT_DETAILS: 'RESET_PROJECT_DETAILS',
  MERGE_PROJECT_FILES: 'MERGE_PROJECT_FILES',
  RESET_PROJECT_FILES: 'RESET_PROJECT_FILES',
  MERGE_PROJECT_QOUTATION: 'MERGE_PROJECT_QOUTATION',
  RESET_PROJECT_QOUTATION: 'RESET_PROJECT_QOUTATION',
  MERGE_PROJECT_SERVICES: 'MERGE_PROJECT_SERVICES',
  RESET_PROJECT_SERVICES: 'RESET_PROJECT_SERVICES',
  MERGE_PROJECT_LIST: 'MERGE_PROJECT_LIST',
  RESET_PROJECT_LIST: 'RESET_PROJECT_LIST'
};

export const notificationActionType = {
  MERGE_NOTIFICATION_LIST: 'MERGE_NOTIFICATION_LIST',
  RESET_NOTIFICATION_LIST: 'RESET_NOTIFICATION_LIST'
};
